inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

require:
  - rubocop-performance
  - rubocop-rspec

# so that it propery excludes vendor in circleci see: https://github.com/rubocop-hq/rubocop/issues/6398
inherit_mode:
  merge:
    - Exclude

AllCops:
  UseCache: true
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

# our style changes: disabling style rules we aren't interested in
Style/StringLiterals:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Lint changes
Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/EmptyLiteral:
  Enabled: true
Style/AndOr:
  EnforcedStyle: conditionals
Style/RescueModifier:
  Severity: warning
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# Things we may want to tighten down later
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 400
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Max: 2000
Metrics/CyclomaticComplexity:
  Max: 100
Metrics/PerceivedComplexity:
  Max: 100
Performance/SelectMap:
  Enabled: false
Performance/OpenStruct:
  Enabled: false
