---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/user":
    post:
      summary: Create a new user
      tags:
      - Registration
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    name:
                      type: string
  "/api/v1/sessions":
    post:
      summary: Login a user
      tags:
      - Session
      parameters: []
      responses:
        '200':
          description: successful
          headers:
            authorization:
              example: Bearer {{token}}
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                        example: Logged in successfully
                      user:
                        type: object
                        properties:
                          email:
                            type: string
                          name:
                            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string   
    delete:
      summary: Logout a user
      tags:
      - Session
      parameters:
      - name: Authorization
        in: header
        example: Bearer {{token}}
        schema:
          type: string
        required: true
      responses:
        '200':
          description: deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                        example: Logged out successfully
servers:
- url: http://localhost:3000
  description: Local Server
  variables:
    defaultHost:
      default: localhost:3000
- url: https://api.staging.impact-core.com
  description: Staging Server
  variables:
    defaultHost:
      default: api.staging.impact-core.com
- url: https://api.impact-core.com
  description: Production Server
  variables:
    defaultHost:
      default: api.impact-core.com

